apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: client
  template:
    metadata:
      labels:
        components: client
    spec:
      containers:
        - name: client
          image: nginx:latest
          ports:
            - containerPort: 80
