apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mysql
  template:
    metadata:
      labels:
        component: mysql
    spec:
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-persistent-volume-claim
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
              subPath: mysql
          envFrom:
            - configMapRef:
                name: mysql-configmap
            - secretKeyRef:
                name: app-secret
                key: MYSQL_PASS
          args:
            [
              "--default-authentication-plugin=mysql_native_password",
              "--lower_case_table_names=1",
              "--character-set-server=utf8mb4",
              "--collation-server=utf8mb4_unicode_ci",
            ]
